# Generated by: python -m pwiz

from peewee import *

database = PostgresqlDatabase("mydb")


class BaseModel(Model):
    class Meta:
        database = database


class Users(BaseModel):
    name = CharField(max_length=100)
    email = CharField(max_length=254, unique=True)
    created_at = DateTimeField(null=True)

    class Meta:
        table_name = "users"
