# Generated by: sqlacodegen --generator sqlmodels

from datetime import datetime
from typing import Optional

from sqlmodel import Field, SQLModel


class Users(SQLModel, table=True):
    __tablename__ = "users"

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(max_length=100)
    email: str = Field(max_length=254, unique=True)
    created_at: Optional[datetime] = None
