// Generated by: mikro-orm generate-entities

import { Entity, PrimaryKey, Property } from "@mikro-orm/core";

@Entity({ tableName: "users" })
export class Users {
  @PrimaryKey()
  id!: number;

  @Property({ length: 100 })
  name!: string;

  @Property({ length: 254, unique: true })
  email!: string;

  @Property({ type: "timestamptz", nullable: true })
  createdAt?: Date;
}
