// Generated by: npx kysely-codegen

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Users {
  id: Generated<number>;
  name: string;
  email: string;
  created_at: Timestamp | null;
}

export interface DB {
  users: Users;
}
