# Generated by: aerich inspectdb

from tortoise import fields
from tortoise.models import Model


class Users(Model):
    id = fields.IntField(primary_key=True)
    name = fields.CharField(max_length=100)
    email = fields.CharField(max_length=254, unique=True)
    created_at = fields.DatetimeField(null=True)

    class Meta:
        table = "users"
