// Generated by: typeorm-model-generator

import { Column, Entity, Index, PrimaryGeneratedColumn } from "typeorm";

@Entity("users")
export class Users {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("varchar", { length: 100 })
  name: string;

  @Index({ unique: true })
  @Column("varchar", { length: 254 })
  email: string;

  @Column("timestamptz", { nullable: true })
  created_at: Date | null;
}
