// Generated by: sequelize-auto

import { DataTypes, Model } from "sequelize";
import type { Sequelize } from "sequelize";

export class Users extends Model {
  declare id: number;
  declare name: string;
  declare email: string;
  declare created_at: Date | null;
}

export function initModels(sequelize: Sequelize) {
  Users.init(
    {
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
      },
      name: {
        type: DataTypes.STRING(100),
        allowNull: false,
      },
      email: {
        type: DataTypes.STRING(254),
        allowNull: false,
        unique: true,
      },
      created_at: {
        type: DataTypes.DATE,
        allowNull: true,
      },
    },
    { sequelize, tableName: "users" }
  );
}
